apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: frontend
      bazel:
        target: //services/frontend:image.tar
        args:
        - --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64

    - image: order
      context: services/order

profiles:
- name: dev
  build:
    local:
      push: false
  deploy:
    statusCheckDeadlineSeconds: 300
    kubeContext: custom
  portForward:
    - resourceType: deployment
      resourceName: frontend-v1
      namespace: default
      port: 3000
      localPort: 3000
  activation:
    - command: dev