apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: frontend
      requires:
        - image: order
      bazel:
        target: //services/frontend:image.tar
        args:
        - --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64

    - image: order
      bazel:
        target: //services/order:image.tar
        args:
          - --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64
portForward:
  - resourceType: deployment
    resourceName: frontend-v1
    port: 3000
    localPort: 3000