apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
imagePullSecrets:
- name: ecr-secret
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
spec:
  ports:
    - port: 80
      name: http
      targetPort: 3000
  selector:
    app: frontend
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v1
  labels:
    app: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: frontend
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 1
            periodSeconds: 100
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            periodSeconds: 100