apiVersion: v1
kind: ServiceAccount
metadata:
  name: order
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::270878775604:role/learngo-stage-eks-irsa
    eks.amazonaws.com/sts-regional-endpoints: "true"

imagePullSecrets:
- name: ecr-secret
---

apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
    service: order
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: order
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-v1
  labels:
    app: order
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
      version: v1
  template:
    metadata:
      labels:
        app: order
        version: v1
    spec:
      serviceAccountName: order
      containers:
        - name: order
          image: 270878775604.dkr.ecr.us-east-2.amazonaws.com/order:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080