apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecrets }}